name: verygoodcoffee

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - post_submission_updates
  pull_request:
    branches:
      - main
      - post_submission_updates

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      coveracge_exludes: "lib/l10n/arb/app_localizations.dart"

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
      modified_files_only: false
